runtime: php
env: flex
runtime_config:
  document_root: public
env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:S+uUhQqryHyUM5mYGyknh1YiHHlADGMNrGopkieDgp4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie